import Head from 'next/head'
import React from 'react';
import { setComments } from '../components/api/sentim-api';
import styles from '../styles/Home.module.css'

export default function Home() {

  function onSubmit() {
    if (process.browser) {
      console.log(setComentarios(document.getElementById('inputCommet').nodeValue));
    }
    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.grid}>
          <p className={styles.title}>
            Indique el comentatio que desee enviar
          </p>
          <input id='inputCommet' type='text'></input>
        </div>

        <button onClick={()=>{
          if (process.browser) {
            setComments(document.getElementById('inputCommet').value).then(res => console.log(res));
          }
        }}>Enviar comentario</button>
      </main>
    </div>
  )
}
