import Head from 'next/head'
import React from 'react';
import { setComments } from '../components/api/sentim-api';
import styles from '../styles/Home.module.css'

export default function Home() {

  const [comments, setComment] = React.useState([]);

  function onSubmit() {
    if (process.browser) {
      setComment([...comments, document.getElementById('inputCommet').value]);
      document.getElementById('inputCommet').value = '';
    }
  }

  // const showCommets = async(c) => {
  //   // if (process.browser) {
  //     comments.forEach(comment => {
  //       const dsjkf = await setComments(comment)
  //     })
  //   }
  // // }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.grid}>
          <p className={styles.title}>
            Indique el comentario que desee enviar
          </p>
          <input id='inputCommet' type='text'></input>
        </div>

        <button id='buttonSend' onClick={()=>{
          onSubmit();
        }}>Enviar comentario</button>

        <button id='buttonResults' onClick={async()=>{
          if (process.browser) {
            comments.forEach(comment => {
              setComments(comment).then(data => console.log(data));
            })
          }
          
          console.log(comments);
        }}>Generar resultados</button>

        <div style={
          {
            width: '80%',
          }
        }>
          <a id='divResult'></a>
        </div>
      </main>
    </div>
  )
}
